export function serverInternalError() {
  const message = 'Um erro inesperado aconteceu. Por favor, tente novamente mais tarde!';
  return message;
}
